"""add file_path to post_media

Revision ID: 00a0a8363394
Revises: 9512c783e9aa
Create Date: 2026-08-07 14:53:26.925599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a0a8363394'
down_revision: Union[str, Sequence[str], None] = '9512c783e9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_media', sa.Column('file_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_media', 'file_path')
    # ### end Alembic commands ###
