"""add updated_at to campaigns

Revision ID: 581d0ae7dcaa
Revises: 7cf84a5ab370
Create Date: 2026-08-16 08:04:38.786490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581d0ae7dcaa'
down_revision: Union[str, Sequence[str], None] = '7cf84a5ab370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'updated_at')
    # ### end Alembic commands ###
