"""create business assignment table

Revision ID: 70cde057359e
Revises: 1ad82b074401
Create Date: 2026-07-29 15:54:19.840705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70cde057359e'
down_revision: Union[str, Sequence[str], None] = '1ad82b074401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_user_id', sa.Integer(), nullable=False),
    sa.Column('marketing_team_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['marketing_team_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_assignments_id'), 'business_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_assignments_id'), table_name='business_assignments')
    op.drop_table('business_assignments')
    # ### end Alembic commands ###
