"""improve social account model

Revision ID: 79d53b7498f6
Revises: 37006afd9c52
Create Date: 2026-07-30 13:45:17.075298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d53b7498f6'
down_revision: Union[str, Sequence[str], None] = '37006afd9c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('social_accounts', 'is_connected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('social_accounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index('idx_social_account_account_id', 'social_accounts', ['account_id'], unique=False)
    op.create_index('idx_social_account_platform', 'social_accounts', ['platform'], unique=False)
    op.create_index(op.f('ix_social_accounts_user_id'), 'social_accounts', ['user_id'], unique=False)
    op.create_unique_constraint('unique_platform_account', 'social_accounts', ['platform', 'account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_platform_account', 'social_accounts', type_='unique')
    op.drop_index(op.f('ix_social_accounts_user_id'), table_name='social_accounts')
    op.drop_index('idx_social_account_platform', table_name='social_accounts')
    op.drop_index('idx_social_account_account_id', table_name='social_accounts')
    op.alter_column('social_accounts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('social_accounts', 'is_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('social_accounts', 'updated_at')
    # ### end Alembic commands ###
