"""add login_devices table

Revision ID: 7cf84a5ab370
Revises: 7f532ce533dc
Create Date: 2026-08-15 23:39:18.638301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf84a5ab370'
down_revision: Union[str, Sequence[str], None] = '7f532ce533dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_devices_fingerprint'), 'login_devices', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_login_devices_id'), 'login_devices', ['id'], unique=False)
    op.create_index(op.f('ix_login_devices_user_id'), 'login_devices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_devices_user_id'), table_name='login_devices')
    op.drop_index(op.f('ix_login_devices_id'), table_name='login_devices')
    op.drop_index(op.f('ix_login_devices_fingerprint'), table_name='login_devices')
    op.drop_table('login_devices')
    # ### end Alembic commands ###
