"""extend notifications table for module 7

Revision ID: 941dbcb97ffb
Revises: 471a6d3f7c4e
Create Date: 2026-08-15 19:54:43.876436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941dbcb97ffb'
down_revision: Union[str, Sequence[str], None] = '471a6d3f7c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('notifications', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('notifications', sa.Column('delivery_channel', sa.String(length=20), nullable=False, server_default='in_app'))
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_publish_logs_scheduled_post_id'), 'publish_logs', ['scheduled_post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publish_logs_scheduled_post_id'), table_name='publish_logs')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'delivery_channel')
    op.drop_column('notifications', 'category')
    op.drop_column('notifications', 'title')
    # ### end Alembic commands ###
