"""add business assignments table

Revision ID: 9dfdc1a12ba9
Revises: 00a0a8363394
Create Date: 2026-08-07 16:54:17.893769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dfdc1a12ba9'
down_revision: Union[str, Sequence[str], None] = '00a0a8363394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_business_marketing', 'business_assignments', ['business_user_id', 'marketing_team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_business_marketing', 'business_assignments', type_='unique')
    # ### end Alembic commands ###
