"""add updated_at to users

Revision ID: d1b1284f1d48
Revises: 79d53b7498f6
Create Date: 2026-07-30 14:43:51.748844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b1284f1d48'
down_revision: Union[str, Sequence[str], None] = '79d53b7498f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_social_account_account_id'), table_name='social_accounts')
    op.drop_index(op.f('idx_social_account_platform'), table_name='social_accounts')
    op.create_index('idx_social_account_id', 'social_accounts', ['account_id'], unique=False)
    op.create_index('idx_social_platform', 'social_accounts', ['platform'], unique=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_index('idx_social_platform', table_name='social_accounts')
    op.drop_index('idx_social_account_id', table_name='social_accounts')
    op.create_index(op.f('idx_social_account_platform'), 'social_accounts', ['platform'], unique=False)
    op.create_index(op.f('idx_social_account_account_id'), 'social_accounts', ['account_id'], unique=False)
    # ### end Alembic commands ###
