import { Campaign } from "@/types/campaign";

export const mockCampaigns: Campaign[] = [
  {
    id: 1,
    name: "Nike Summer Sale",
    objective: "Product Launch",
    budget: 200000,
    category: "Marketing",
    priority: "High",
    status: "Running",
    startDate: "2026-07-01",
    endDate: "2026-07-31",
    progress: 72,
    totalPosts: 25,
    completedPosts: 18,
  },
  {
    id: 2,
    name: "Samsung Independence Offer",
    objective: "Brand Awareness",
    budget: 150000,
    category: "Promotion",
    priority: "Medium",
    status: "Draft",
    startDate: "2026-08-01",
    endDate: "2026-08-20",
    progress: 20,
    totalPosts: 15,
    completedPosts: 3,
  },
  {
    id: 3,
    name: "Apple Back to School",
    objective: "Product Promotion",
    budget: 300000,
    category: "Education",
    priority: "High",
    status: "Completed",
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    progress: 100,
    totalPosts: 30,
    completedPosts: 30,
  },
];